
import numpy as np
import faiss
from loguru import logger
import os

class VectorSearch:
    """
    Handles similarity search using FAISS (Cosine Similarity).
    """
    def __init__(self, dimension=512, index_file="index.faiss"):
        self.dimension = dimension
        self.index_file = index_file
        
        # Inner Product with normalized vectors = Cosine Similarity
        self.index = faiss.IndexFlatIP(dimension)
        
        # ID Mapping: FAISS index -> Real Identity Name (or DB ID)
        self.id_map = {} # int_index -> str_identity
        self.next_id = 0
        
        if os.path.exists(index_file):
            self.load()
        else:
             # Try loading legacy features from add_persons.py
             self.load_legacy_features("datasets/face_features/feature.npz")
            
        logger.info(f"VectorSearch initialized. Dimension: {dimension}. Loaded {self.index.ntotal} vectors.")

    def load_legacy_features(self, path):
        """Loads features from .npz file generated by add_persons.py"""
        if not os.path.exists(path):
            logger.warning(f"No legacy features found at {path}")
            return
            
        try:
            data = np.load(path)
            names = data["images_name"]
            embs = data["images_emb"]
            
            logger.info(f"Loading {len(names)} features from {path}")
            
            for name, emb in zip(names, embs):
                # Ensure embedding is 512-dim
                if emb.shape[0] != self.dimension:
                    continue
                self.add(emb, str(name))
                
        except Exception as e:
            logger.error(f"Failed to load legacy features: {e}")

    def add(self, embedding: np.ndarray, identity: str):
        """
        Adds embedding to index.
        """
        if embedding.shape[0] != self.dimension:
            logger.error(f"Embedding dimension mismatch: {embedding.shape[0]} vs {self.dimension}")
            return
            
        # Normalize for cosine similarity
        faiss.normalize_L2(embedding.reshape(1, -1))
        
        self.index.add(embedding.reshape(1, -1))
        self.id_map[self.next_id] = identity
        self.next_id += 1
        return True

    def search(self, embedding: np.ndarray, threshold: float = 0.25):
        """
        Search for identity.
        Returns: identity (str), score (float)
        """
        if self.index.ntotal == 0:
            return "Unknown", 0.0

        # Normalize
        emb = embedding.reshape(1, -1).astype('float32') # FAISS needs float32
        faiss.normalize_L2(emb)
        
        D, I = self.index.search(emb, 1) # Top 1
        
        score = D[0][0]
        idx = I[0][0]
        
        if idx != -1:
            # FORCE PRINT for debugging
            print(f"DEBUG: Found {self.id_map.get(idx, 'Unknown')} | Score: {score:.4f} | Thresh: {threshold}")
            
            if score >= threshold:
                identity = self.id_map.get(idx, "Unknown")
                return identity, float(score)
            elif score > 0.1:
                 print(f"WARNING: Near miss: {self.id_map.get(idx, 'Unknown')} with score {score:.4f}")
        
        return "Unknown", float(score)

    def save(self):
        faiss.write_index(self.index, self.index_file)
        # Also need to save id_map. For now, skipping persistent map for simplicity/demo 
        # unless requested. Ideally pickle it.
        pass

    def load(self):
        try:
            self.index = faiss.read_index(self.index_file)
            # Reconstruct map? Impossible without auxiliary file.
            pass 
        except Exception as e:
            logger.error(f"Failed to load index: {e}")
